### ISSUE TITLE
netease-dl-go down -s 554242032 show connection refused

### ISSUE THREAD

**Issue by TONYHOKAN** [Trytwice/netease-dl-go#1]
hi, thanks for your wonderful tool, but i run your tool in docker 

docker run --rm --name golang -it golang:1.12rc1-stretch

seems not working:

root@509870f742f8:/go/bin# netease-dl-go search 生僻字
2019/02/24 09:40:57 response.Status error: check http response
root@509870f742f8:/go/bin# netease-dl-go down -s 554242032
2019/02/24 09:41:15 Get http://m10.music.126.net/20190224180111/2a2c37f99ca5042aff91f3de6f497829/ymusic/ed37/c003/eb6a/ed576dd23f5478f81122bef8678890a4.mp3: dial tcp 127.0.0.1:80: connect: connection refused
root@509870f742f8:/go/bin# netease-dl-go s 生僻字 起风了
2019/02/24 09:42:37 response.Status error: check http response

**Comment by Trytwice** [comment]
Thanks for your feedback.I run the app in the same environment and it works fine. 

**response.Status error: check http response** this error means that the http request failed. 

I have no idea how to fix it. Maybe you can try to modify the **User-Agent** in 
 downloader/download.go
